name: CD
# 태그가 생성될 때 배포 워크플로우가 실행됩니다.
on:
  push:
    tags:
      - "*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          target: production
          tags: ${{ secrets.DOCKER_USERNAME }}/krx_lm_train:${{ github.ref_name }}
